# Generated by Django 5.0.1 on 2024-01-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notevault', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='shared_with',
        ),
    ]
